# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.AccountInfo do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountAgeIndicator",
    :"accountChangeDate",
    :"accountChangeIndicator",
    :"accountCreationDate",
    :"accountType",
    :"addCardAttemptsDay",
    :"deliveryAddressUsageDate",
    :"deliveryAddressUsageIndicator",
    :"homePhone",
    :"mobilePhone",
    :"passwordChangeDate",
    :"passwordChangeIndicator",
    :"pastTransactionsDay",
    :"pastTransactionsYear",
    :"paymentAccountAge",
    :"paymentAccountIndicator",
    :"purchasesLast6Months",
    :"suspiciousActivity",
    :"workPhone"
  ]

  @type t :: %__MODULE__{
    :"accountAgeIndicator" => String.t | nil,
    :"accountChangeDate" => DateTime.t | nil,
    :"accountChangeIndicator" => String.t | nil,
    :"accountCreationDate" => DateTime.t | nil,
    :"accountType" => String.t | nil,
    :"addCardAttemptsDay" => integer() | nil,
    :"deliveryAddressUsageDate" => DateTime.t | nil,
    :"deliveryAddressUsageIndicator" => String.t | nil,
    :"homePhone" => String.t | nil,
    :"mobilePhone" => String.t | nil,
    :"passwordChangeDate" => DateTime.t | nil,
    :"passwordChangeIndicator" => String.t | nil,
    :"pastTransactionsDay" => integer() | nil,
    :"pastTransactionsYear" => integer() | nil,
    :"paymentAccountAge" => DateTime.t | nil,
    :"paymentAccountIndicator" => String.t | nil,
    :"purchasesLast6Months" => integer() | nil,
    :"suspiciousActivity" => boolean() | nil,
    :"workPhone" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.AccountInfo do
  def decode(value, _options) do
    value
  end
end

