# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.AchDetails do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"bankAccountNumber",
    :"bankLocationId",
    :"encryptedBankAccountNumber",
    :"encryptedBankLocationId",
    :"ownerName",
    :"recurringDetailReference",
    :"storedPaymentMethodId",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"bankAccountNumber" => String.t,
    :"bankLocationId" => String.t | nil,
    :"encryptedBankAccountNumber" => String.t | nil,
    :"encryptedBankLocationId" => String.t | nil,
    :"ownerName" => String.t | nil,
    :"recurringDetailReference" => String.t | nil,
    :"storedPaymentMethodId" => String.t | nil,
    :"type" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.AchDetails do
  def decode(value, _options) do
    value
  end
end

