# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.AdditionalDataTemporaryServices do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"enhancedSchemeData.customerReference",
    :"enhancedSchemeData.employeeName",
    :"enhancedSchemeData.jobDescription",
    :"enhancedSchemeData.regularHoursRate",
    :"enhancedSchemeData.regularHoursWorked",
    :"enhancedSchemeData.requestName",
    :"enhancedSchemeData.tempStartDate",
    :"enhancedSchemeData.tempWeekEnding",
    :"enhancedSchemeData.totalTaxAmount"
  ]

  @type t :: %__MODULE__{
    :"enhancedSchemeData.customerReference" => String.t | nil,
    :"enhancedSchemeData.employeeName" => String.t | nil,
    :"enhancedSchemeData.jobDescription" => String.t | nil,
    :"enhancedSchemeData.regularHoursRate" => String.t | nil,
    :"enhancedSchemeData.regularHoursWorked" => String.t | nil,
    :"enhancedSchemeData.requestName" => String.t | nil,
    :"enhancedSchemeData.tempStartDate" => String.t | nil,
    :"enhancedSchemeData.tempWeekEnding" => String.t | nil,
    :"enhancedSchemeData.totalTaxAmount" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.AdditionalDataTemporaryServices do
  def decode(value, _options) do
    value
  end
end

