# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.AdditionalDataCarRental do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"carRental.checkOutDate",
    :"carRental.customerServiceTollFreeNumber",
    :"carRental.daysRented",
    :"carRental.fuelCharges",
    :"carRental.insuranceCharges",
    :"carRental.locationCity",
    :"carRental.locationCountry",
    :"carRental.locationStateProvince",
    :"carRental.noShowIndicator",
    :"carRental.oneWayDropOffCharges",
    :"carRental.rate",
    :"carRental.rateIndicator",
    :"carRental.rentalAgreementNumber",
    :"carRental.rentalClassId",
    :"carRental.renterName",
    :"carRental.returnCity",
    :"carRental.returnCountry",
    :"carRental.returnDate",
    :"carRental.returnLocationId",
    :"carRental.returnStateProvince",
    :"carRental.taxExemptIndicator",
    :"travelEntertainmentAuthData.duration",
    :"travelEntertainmentAuthData.market"
  ]

  @type t :: %__MODULE__{
    :"carRental.checkOutDate" => String.t | nil,
    :"carRental.customerServiceTollFreeNumber" => String.t | nil,
    :"carRental.daysRented" => String.t | nil,
    :"carRental.fuelCharges" => String.t | nil,
    :"carRental.insuranceCharges" => String.t | nil,
    :"carRental.locationCity" => String.t | nil,
    :"carRental.locationCountry" => String.t | nil,
    :"carRental.locationStateProvince" => String.t | nil,
    :"carRental.noShowIndicator" => String.t | nil,
    :"carRental.oneWayDropOffCharges" => String.t | nil,
    :"carRental.rate" => String.t | nil,
    :"carRental.rateIndicator" => String.t | nil,
    :"carRental.rentalAgreementNumber" => String.t | nil,
    :"carRental.rentalClassId" => String.t | nil,
    :"carRental.renterName" => String.t | nil,
    :"carRental.returnCity" => String.t | nil,
    :"carRental.returnCountry" => String.t | nil,
    :"carRental.returnDate" => String.t | nil,
    :"carRental.returnLocationId" => String.t | nil,
    :"carRental.returnStateProvince" => String.t | nil,
    :"carRental.taxExemptIndicator" => String.t | nil,
    :"travelEntertainmentAuthData.duration" => String.t | nil,
    :"travelEntertainmentAuthData.market" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.AdditionalDataCarRental do
  def decode(value, _options) do
    value
  end
end

