# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.AdditionalDataCommon do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"RequestedTestErrorResponseCode",
    :"authorisationType",
    :"customRoutingFlag",
    :"industryUsage",
    :"networkTxReference",
    :"overwriteBrand",
    :"subMerchantCity",
    :"subMerchantCountry",
    :"subMerchantID",
    :"subMerchantName",
    :"subMerchantPostalCode",
    :"subMerchantState",
    :"subMerchantStreet",
    :"subMerchantTaxId"
  ]

  @type t :: %__MODULE__{
    :"RequestedTestErrorResponseCode" => String.t | nil,
    :"authorisationType" => String.t | nil,
    :"customRoutingFlag" => String.t | nil,
    :"industryUsage" => String.t | nil,
    :"networkTxReference" => String.t | nil,
    :"overwriteBrand" => String.t | nil,
    :"subMerchantCity" => String.t | nil,
    :"subMerchantCountry" => String.t | nil,
    :"subMerchantID" => String.t | nil,
    :"subMerchantName" => String.t | nil,
    :"subMerchantPostalCode" => String.t | nil,
    :"subMerchantState" => String.t | nil,
    :"subMerchantStreet" => String.t | nil,
    :"subMerchantTaxId" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.AdditionalDataCommon do
  def decode(value, _options) do
    value
  end
end

