# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.AdditionalDataRisk do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"riskdata.[customFieldName]",
    :"riskdata.basket.item[itemNr].amountPerItem",
    :"riskdata.basket.item[itemNr].brand",
    :"riskdata.basket.item[itemNr].category",
    :"riskdata.basket.item[itemNr].color",
    :"riskdata.basket.item[itemNr].currency",
    :"riskdata.basket.item[itemNr].itemID",
    :"riskdata.basket.item[itemNr].manufacturer",
    :"riskdata.basket.item[itemNr].productTitle",
    :"riskdata.basket.item[itemNr].quantity",
    :"riskdata.basket.item[itemNr].receiverEmail",
    :"riskdata.basket.item[itemNr].size",
    :"riskdata.basket.item[itemNr].sku",
    :"riskdata.basket.item[itemNr].upc",
    :"riskdata.promotions.promotion[itemNr].promotionCode",
    :"riskdata.promotions.promotion[itemNr].promotionDiscountAmount",
    :"riskdata.promotions.promotion[itemNr].promotionDiscountCurrency",
    :"riskdata.promotions.promotion[itemNr].promotionDiscountPercentage",
    :"riskdata.promotions.promotion[itemNr].promotionName",
    :"riskdata.riskProfileReference"
  ]

  @type t :: %__MODULE__{
    :"riskdata.[customFieldName]" => String.t | nil,
    :"riskdata.basket.item[itemNr].amountPerItem" => String.t | nil,
    :"riskdata.basket.item[itemNr].brand" => String.t | nil,
    :"riskdata.basket.item[itemNr].category" => String.t | nil,
    :"riskdata.basket.item[itemNr].color" => String.t | nil,
    :"riskdata.basket.item[itemNr].currency" => String.t | nil,
    :"riskdata.basket.item[itemNr].itemID" => String.t | nil,
    :"riskdata.basket.item[itemNr].manufacturer" => String.t | nil,
    :"riskdata.basket.item[itemNr].productTitle" => String.t | nil,
    :"riskdata.basket.item[itemNr].quantity" => String.t | nil,
    :"riskdata.basket.item[itemNr].receiverEmail" => String.t | nil,
    :"riskdata.basket.item[itemNr].size" => String.t | nil,
    :"riskdata.basket.item[itemNr].sku" => String.t | nil,
    :"riskdata.basket.item[itemNr].upc" => String.t | nil,
    :"riskdata.promotions.promotion[itemNr].promotionCode" => String.t | nil,
    :"riskdata.promotions.promotion[itemNr].promotionDiscountAmount" => String.t | nil,
    :"riskdata.promotions.promotion[itemNr].promotionDiscountCurrency" => String.t | nil,
    :"riskdata.promotions.promotion[itemNr].promotionDiscountPercentage" => String.t | nil,
    :"riskdata.promotions.promotion[itemNr].promotionName" => String.t | nil,
    :"riskdata.riskProfileReference" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.AdditionalDataRisk do
  def decode(value, _options) do
    value
  end
end

