# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.AdditionalDataRiskStandalone do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"PayPal.CountryCode",
    :"PayPal.EmailId",
    :"PayPal.FirstName",
    :"PayPal.LastName",
    :"PayPal.PayerId",
    :"PayPal.Phone",
    :"PayPal.ProtectionEligibility",
    :"PayPal.TransactionId",
    :"avsResultRaw",
    :"bin",
    :"cvcResultRaw",
    :"riskToken",
    :"threeDAuthenticated",
    :"threeDOffered",
    :"tokenDataType"
  ]

  @type t :: %__MODULE__{
    :"PayPal.CountryCode" => String.t | nil,
    :"PayPal.EmailId" => String.t | nil,
    :"PayPal.FirstName" => String.t | nil,
    :"PayPal.LastName" => String.t | nil,
    :"PayPal.PayerId" => String.t | nil,
    :"PayPal.Phone" => String.t | nil,
    :"PayPal.ProtectionEligibility" => String.t | nil,
    :"PayPal.TransactionId" => String.t | nil,
    :"avsResultRaw" => String.t | nil,
    :"bin" => String.t | nil,
    :"cvcResultRaw" => String.t | nil,
    :"riskToken" => String.t | nil,
    :"threeDAuthenticated" => String.t | nil,
    :"threeDOffered" => String.t | nil,
    :"tokenDataType" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.AdditionalDataRiskStandalone do
  def decode(value, _options) do
    value
  end
end

