# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.AdditionalDataLodging do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"lodging.checkInDate",
    :"lodging.checkOutDate",
    :"lodging.customerServiceTollFreeNumber",
    :"lodging.fireSafetyActIndicator",
    :"lodging.folioCashAdvances",
    :"lodging.folioNumber",
    :"lodging.foodBeverageCharges",
    :"lodging.noShowIndicator",
    :"lodging.prepaidExpenses",
    :"lodging.propertyPhoneNumber",
    :"lodging.room1.numberOfNights",
    :"lodging.room1.rate",
    :"lodging.room1.tax",
    :"lodging.totalRoomTax",
    :"lodging.totalTax",
    :"travelEntertainmentAuthData.duration",
    :"travelEntertainmentAuthData.market"
  ]

  @type t :: %__MODULE__{
    :"lodging.checkInDate" => String.t | nil,
    :"lodging.checkOutDate" => String.t | nil,
    :"lodging.customerServiceTollFreeNumber" => String.t | nil,
    :"lodging.fireSafetyActIndicator" => String.t | nil,
    :"lodging.folioCashAdvances" => String.t | nil,
    :"lodging.folioNumber" => String.t | nil,
    :"lodging.foodBeverageCharges" => String.t | nil,
    :"lodging.noShowIndicator" => String.t | nil,
    :"lodging.prepaidExpenses" => String.t | nil,
    :"lodging.propertyPhoneNumber" => String.t | nil,
    :"lodging.room1.numberOfNights" => String.t | nil,
    :"lodging.room1.rate" => String.t | nil,
    :"lodging.room1.tax" => String.t | nil,
    :"lodging.totalRoomTax" => String.t | nil,
    :"lodging.totalTax" => String.t | nil,
    :"travelEntertainmentAuthData.duration" => String.t | nil,
    :"travelEntertainmentAuthData.market" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.AdditionalDataLodging do
  def decode(value, _options) do
    value
  end
end

