# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.AdditionalDataAirline do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"airline.agency_invoice_number",
    :"airline.agency_plan_name",
    :"airline.airline_code",
    :"airline.airline_designator_code",
    :"airline.boarding_fee",
    :"airline.computerized_reservation_system",
    :"airline.customer_reference_number",
    :"airline.document_type",
    :"airline.flight_date",
    :"airline.leg.carrier_code",
    :"airline.leg.class_of_travel",
    :"airline.leg.date_of_travel",
    :"airline.leg.depart_airport",
    :"airline.leg.depart_tax",
    :"airline.leg.destination_code",
    :"airline.leg.fare_base_code",
    :"airline.leg.flight_number",
    :"airline.leg.stop_over_code",
    :"airline.passenger.date_of_birth",
    :"airline.passenger.first_name",
    :"airline.passenger.last_name",
    :"airline.passenger.telephone_number",
    :"airline.passenger.traveller_type",
    :"airline.passenger_name",
    :"airline.ticket_issue_address",
    :"airline.ticket_number",
    :"airline.travel_agency_code",
    :"airline.travel_agency_name"
  ]

  @type t :: %__MODULE__{
    :"airline.agency_invoice_number" => String.t | nil,
    :"airline.agency_plan_name" => String.t | nil,
    :"airline.airline_code" => String.t | nil,
    :"airline.airline_designator_code" => String.t | nil,
    :"airline.boarding_fee" => String.t | nil,
    :"airline.computerized_reservation_system" => String.t | nil,
    :"airline.customer_reference_number" => String.t | nil,
    :"airline.document_type" => String.t | nil,
    :"airline.flight_date" => String.t | nil,
    :"airline.leg.carrier_code" => String.t | nil,
    :"airline.leg.class_of_travel" => String.t | nil,
    :"airline.leg.date_of_travel" => String.t | nil,
    :"airline.leg.depart_airport" => String.t | nil,
    :"airline.leg.depart_tax" => String.t | nil,
    :"airline.leg.destination_code" => String.t | nil,
    :"airline.leg.fare_base_code" => String.t | nil,
    :"airline.leg.flight_number" => String.t | nil,
    :"airline.leg.stop_over_code" => String.t | nil,
    :"airline.passenger.date_of_birth" => String.t | nil,
    :"airline.passenger.first_name" => String.t | nil,
    :"airline.passenger.last_name" => String.t | nil,
    :"airline.passenger.telephone_number" => String.t | nil,
    :"airline.passenger.traveller_type" => String.t | nil,
    :"airline.passenger_name" => String.t,
    :"airline.ticket_issue_address" => String.t | nil,
    :"airline.ticket_number" => String.t | nil,
    :"airline.travel_agency_code" => String.t | nil,
    :"airline.travel_agency_name" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.AdditionalDataAirline do
  def decode(value, _options) do
    value
  end
end

