# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.AdditionalDataOpenInvoice do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"openinvoicedata.merchantData",
    :"openinvoicedata.numberOfLines",
    :"openinvoicedataLine[itemNr].currencyCode",
    :"openinvoicedataLine[itemNr].description",
    :"openinvoicedataLine[itemNr].itemAmount",
    :"openinvoicedataLine[itemNr].itemId",
    :"openinvoicedataLine[itemNr].itemVatAmount",
    :"openinvoicedataLine[itemNr].itemVatPercentage",
    :"openinvoicedataLine[itemNr].numberOfItems",
    :"openinvoicedataLine[itemNr].returnShippingCompany",
    :"openinvoicedataLine[itemNr].returnTrackingNumber",
    :"openinvoicedataLine[itemNr].returnTrackingUri",
    :"openinvoicedataLine[itemNr].shippingCompany",
    :"openinvoicedataLine[itemNr].shippingMethod",
    :"openinvoicedataLine[itemNr].trackingNumber",
    :"openinvoicedataLine[itemNr].trackingUri",
    :"openinvoicedataLine[itemNr].vatCategory"
  ]

  @type t :: %__MODULE__{
    :"openinvoicedata.merchantData" => String.t | nil,
    :"openinvoicedata.numberOfLines" => String.t | nil,
    :"openinvoicedataLine[itemNr].currencyCode" => String.t | nil,
    :"openinvoicedataLine[itemNr].description" => String.t | nil,
    :"openinvoicedataLine[itemNr].itemAmount" => String.t | nil,
    :"openinvoicedataLine[itemNr].itemId" => String.t | nil,
    :"openinvoicedataLine[itemNr].itemVatAmount" => String.t | nil,
    :"openinvoicedataLine[itemNr].itemVatPercentage" => String.t | nil,
    :"openinvoicedataLine[itemNr].numberOfItems" => String.t | nil,
    :"openinvoicedataLine[itemNr].returnShippingCompany" => String.t | nil,
    :"openinvoicedataLine[itemNr].returnTrackingNumber" => String.t | nil,
    :"openinvoicedataLine[itemNr].returnTrackingUri" => String.t | nil,
    :"openinvoicedataLine[itemNr].shippingCompany" => String.t | nil,
    :"openinvoicedataLine[itemNr].shippingMethod" => String.t | nil,
    :"openinvoicedataLine[itemNr].trackingNumber" => String.t | nil,
    :"openinvoicedataLine[itemNr].trackingUri" => String.t | nil,
    :"openinvoicedataLine[itemNr].vatCategory" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.AdditionalDataOpenInvoice do
  def decode(value, _options) do
    value
  end
end

