# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.AdditionalDataRatepay do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ratepay.installmentAmount",
    :"ratepay.interestRate",
    :"ratepay.lastInstallmentAmount",
    :"ratepay.paymentFirstday",
    :"ratepaydata.deliveryDate",
    :"ratepaydata.dueDate",
    :"ratepaydata.invoiceDate",
    :"ratepaydata.invoiceId"
  ]

  @type t :: %__MODULE__{
    :"ratepay.installmentAmount" => String.t | nil,
    :"ratepay.interestRate" => String.t | nil,
    :"ratepay.lastInstallmentAmount" => String.t | nil,
    :"ratepay.paymentFirstday" => String.t | nil,
    :"ratepaydata.deliveryDate" => String.t | nil,
    :"ratepaydata.dueDate" => String.t | nil,
    :"ratepaydata.invoiceDate" => String.t | nil,
    :"ratepaydata.invoiceId" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.AdditionalDataRatepay do
  def decode(value, _options) do
    value
  end
end

