# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.AdditionalDataSubMerchant do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"subMerchant.numberOfSubSellers",
    :"subMerchant.subSeller[subSellerNr].city",
    :"subMerchant.subSeller[subSellerNr].country",
    :"subMerchant.subSeller[subSellerNr].creditSettlementAccount",
    :"subMerchant.subSeller[subSellerNr].creditSettlementAccountType",
    :"subMerchant.subSeller[subSellerNr].creditSettlementAgency",
    :"subMerchant.subSeller[subSellerNr].creditSettlementBank",
    :"subMerchant.subSeller[subSellerNr].debitSettlementAccount",
    :"subMerchant.subSeller[subSellerNr].debitSettlementAccountType",
    :"subMerchant.subSeller[subSellerNr].debitSettlementAgency",
    :"subMerchant.subSeller[subSellerNr].debitSettlementBank",
    :"subMerchant.subSeller[subSellerNr].id",
    :"subMerchant.subSeller[subSellerNr].mcc",
    :"subMerchant.subSeller[subSellerNr].name",
    :"subMerchant.subSeller[subSellerNr].postalCode",
    :"subMerchant.subSeller[subSellerNr].state",
    :"subMerchant.subSeller[subSellerNr].street",
    :"subMerchant.subSeller[subSellerNr].taxId"
  ]

  @type t :: %__MODULE__{
    :"subMerchant.numberOfSubSellers" => String.t | nil,
    :"subMerchant.subSeller[subSellerNr].city" => String.t | nil,
    :"subMerchant.subSeller[subSellerNr].country" => String.t | nil,
    :"subMerchant.subSeller[subSellerNr].creditSettlementAccount" => String.t | nil,
    :"subMerchant.subSeller[subSellerNr].creditSettlementAccountType" => String.t | nil,
    :"subMerchant.subSeller[subSellerNr].creditSettlementAgency" => String.t | nil,
    :"subMerchant.subSeller[subSellerNr].creditSettlementBank" => String.t | nil,
    :"subMerchant.subSeller[subSellerNr].debitSettlementAccount" => String.t | nil,
    :"subMerchant.subSeller[subSellerNr].debitSettlementAccountType" => String.t | nil,
    :"subMerchant.subSeller[subSellerNr].debitSettlementAgency" => String.t | nil,
    :"subMerchant.subSeller[subSellerNr].debitSettlementBank" => String.t | nil,
    :"subMerchant.subSeller[subSellerNr].id" => String.t | nil,
    :"subMerchant.subSeller[subSellerNr].mcc" => String.t | nil,
    :"subMerchant.subSeller[subSellerNr].name" => String.t | nil,
    :"subMerchant.subSeller[subSellerNr].postalCode" => String.t | nil,
    :"subMerchant.subSeller[subSellerNr].state" => String.t | nil,
    :"subMerchant.subSeller[subSellerNr].street" => String.t | nil,
    :"subMerchant.subSeller[subSellerNr].taxId" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.AdditionalDataSubMerchant do
  def decode(value, _options) do
    value
  end
end

