# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.AdditionalData3DSecure do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"allow3DS2",
    :"executeThreeD",
    :"mpiImplementationType",
    :"scaExemption",
    :"threeDSVersion"
  ]

  @type t :: %__MODULE__{
    :"allow3DS2" => String.t | nil,
    :"executeThreeD" => String.t | nil,
    :"mpiImplementationType" => String.t | nil,
    :"scaExemption" => String.t | nil,
    :"threeDSVersion" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.AdditionalData3DSecure do
  def decode(value, _options) do
    value
  end
end

