# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.Avs do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"addressEditable",
    :"enabled"
  ]

  @type t :: %__MODULE__{
    :"addressEditable" => boolean() | nil,
    :"enabled" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.Avs do
  def decode(value, _options) do
    value
  end
end

