# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.BankAccount do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"bankAccountNumber",
    :"bankCity",
    :"bankLocationId",
    :"bankName",
    :"bic",
    :"countryCode",
    :"iban",
    :"ownerName",
    :"taxId"
  ]

  @type t :: %__MODULE__{
    :"bankAccountNumber" => String.t | nil,
    :"bankCity" => String.t | nil,
    :"bankLocationId" => String.t | nil,
    :"bankName" => String.t | nil,
    :"bic" => String.t | nil,
    :"countryCode" => String.t | nil,
    :"iban" => String.t | nil,
    :"ownerName" => String.t | nil,
    :"taxId" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.BankAccount do
  def decode(value, _options) do
    value
  end
end

