# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.CardDetails do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"cupsecureplus.smscode",
    :"cvc",
    :"encryptedCardNumber",
    :"encryptedExpiryMonth",
    :"encryptedExpiryYear",
    :"encryptedSecurityCode",
    :"expiryMonth",
    :"expiryYear",
    :"fundingSource",
    :"holderName",
    :"number",
    :"recurringDetailReference",
    :"storedPaymentMethodId",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"cupsecureplus.smscode" => String.t | nil,
    :"cvc" => String.t | nil,
    :"encryptedCardNumber" => String.t,
    :"encryptedExpiryMonth" => String.t,
    :"encryptedExpiryYear" => String.t,
    :"encryptedSecurityCode" => String.t | nil,
    :"expiryMonth" => String.t | nil,
    :"expiryYear" => String.t | nil,
    :"fundingSource" => String.t | nil,
    :"holderName" => String.t | nil,
    :"number" => String.t | nil,
    :"recurringDetailReference" => String.t | nil,
    :"storedPaymentMethodId" => String.t | nil,
    :"type" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.CardDetails do
  def decode(value, _options) do
    value
  end
end

