# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.CheckoutOneTimePasscodeAction do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"paymentData",
    :"paymentMethodType",
    :"redirect",
    :"resendInterval",
    :"resendMaxAttempts",
    :"resendUrl",
    :"type",
    :"url"
  ]

  @type t :: %__MODULE__{
    :"paymentData" => String.t | nil,
    :"paymentMethodType" => String.t | nil,
    :"redirect" => AdyenCheckoutEx.Model.Redirect.t | nil,
    :"resendInterval" => integer() | nil,
    :"resendMaxAttempts" => integer() | nil,
    :"resendUrl" => String.t | nil,
    :"type" => String.t,
    :"url" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.CheckoutOneTimePasscodeAction do
  import AdyenCheckoutEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"redirect", :struct, AdyenCheckoutEx.Model.Redirect, options)
  end
end

