# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.CheckoutOrder do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"orderData",
    :"pspReference"
  ]

  @type t :: %__MODULE__{
    :"orderData" => String.t,
    :"pspReference" => String.t
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.CheckoutOrder do
  def decode(value, _options) do
    value
  end
end

