# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.CheckoutThreeDs2Action do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"authorisationToken",
    :"paymentData",
    :"paymentMethodType",
    :"subtype",
    :"token",
    :"type",
    :"url"
  ]

  @type t :: %__MODULE__{
    :"authorisationToken" => String.t | nil,
    :"paymentData" => String.t | nil,
    :"paymentMethodType" => String.t | nil,
    :"subtype" => String.t | nil,
    :"token" => String.t | nil,
    :"type" => String.t,
    :"url" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.CheckoutThreeDs2Action do
  def decode(value, _options) do
    value
  end
end

