# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.CheckoutCancelOrderRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"merchantAccount",
    :"order"
  ]

  @type t :: %__MODULE__{
    :"merchantAccount" => String.t,
    :"order" => AdyenCheckoutEx.Model.CheckoutOrder.t
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.CheckoutCancelOrderRequest do
  import AdyenCheckoutEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"order", :struct, AdyenCheckoutEx.Model.CheckoutOrder, options)
  end
end

