# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.CheckoutSdkAction do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"paymentData",
    :"paymentMethodType",
    :"sdkData",
    :"type",
    :"url"
  ]

  @type t :: %__MODULE__{
    :"paymentData" => String.t | nil,
    :"paymentMethodType" => String.t | nil,
    :"sdkData" => %{optional(String.t) => String.t} | nil,
    :"type" => String.t,
    :"url" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.CheckoutSdkAction do
  def decode(value, _options) do
    value
  end
end

