# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.CheckoutBankTransferAction do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"beneficiary",
    :"bic",
    :"downloadUrl",
    :"iban",
    :"paymentMethodType",
    :"reference",
    :"shopperEmail",
    :"totalAmount",
    :"type",
    :"url"
  ]

  @type t :: %__MODULE__{
    :"beneficiary" => String.t | nil,
    :"bic" => String.t | nil,
    :"downloadUrl" => String.t | nil,
    :"iban" => String.t | nil,
    :"paymentMethodType" => String.t | nil,
    :"reference" => String.t | nil,
    :"shopperEmail" => String.t | nil,
    :"totalAmount" => AdyenCheckoutEx.Model.Amount.t | nil,
    :"type" => String.t,
    :"url" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.CheckoutBankTransferAction do
  import AdyenCheckoutEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"totalAmount", :struct, AdyenCheckoutEx.Model.Amount, options)
  end
end

