# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.CheckoutBalanceCheckResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"additionalData",
    :"balance",
    :"fraudResult",
    :"pspReference",
    :"refusalReason",
    :"resultCode",
    :"transactionLimit"
  ]

  @type t :: %__MODULE__{
    :"additionalData" => %{optional(String.t) => String.t} | nil,
    :"balance" => AdyenCheckoutEx.Model.Amount.t,
    :"fraudResult" => AdyenCheckoutEx.Model.FraudResult.t | nil,
    :"pspReference" => String.t | nil,
    :"refusalReason" => String.t | nil,
    :"resultCode" => String.t,
    :"transactionLimit" => AdyenCheckoutEx.Model.Amount.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.CheckoutBalanceCheckResponse do
  import AdyenCheckoutEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"balance", :struct, AdyenCheckoutEx.Model.Amount, options)
    |> deserialize(:"fraudResult", :struct, AdyenCheckoutEx.Model.FraudResult, options)
    |> deserialize(:"transactionLimit", :struct, AdyenCheckoutEx.Model.Amount, options)
  end
end

