# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.CheckoutCreateOrderResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"additionalData",
    :"expiresAt",
    :"fraudResult",
    :"orderData",
    :"pspReference",
    :"reference",
    :"refusalReason",
    :"remainingAmount",
    :"resultCode"
  ]

  @type t :: %__MODULE__{
    :"additionalData" => %{optional(String.t) => String.t} | nil,
    :"expiresAt" => String.t,
    :"fraudResult" => AdyenCheckoutEx.Model.FraudResult.t | nil,
    :"orderData" => String.t,
    :"pspReference" => String.t | nil,
    :"reference" => String.t | nil,
    :"refusalReason" => String.t | nil,
    :"remainingAmount" => AdyenCheckoutEx.Model.Amount.t,
    :"resultCode" => String.t
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.CheckoutCreateOrderResponse do
  import AdyenCheckoutEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"fraudResult", :struct, AdyenCheckoutEx.Model.FraudResult, options)
    |> deserialize(:"remainingAmount", :struct, AdyenCheckoutEx.Model.Amount, options)
  end
end

