# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.Company do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"homepage",
    :"name",
    :"registrationNumber",
    :"registryLocation",
    :"taxId",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"homepage" => String.t | nil,
    :"name" => String.t | nil,
    :"registrationNumber" => String.t | nil,
    :"registryLocation" => String.t | nil,
    :"taxId" => String.t | nil,
    :"type" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.Company do
  def decode(value, _options) do
    value
  end
end

