# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.Configuration do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"avs",
    :"cardHolderName",
    :"installments",
    :"shopperInput"
  ]

  @type t :: %__MODULE__{
    :"avs" => AdyenCheckoutEx.Model.Avs.t | nil,
    :"cardHolderName" => String.t | nil,
    :"installments" => AdyenCheckoutEx.Model.Installments2.t | nil,
    :"shopperInput" => AdyenCheckoutEx.Model.ShopperInput.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.Configuration do
  import AdyenCheckoutEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"avs", :struct, AdyenCheckoutEx.Model.Avs, options)
    |> deserialize(:"installments", :struct, AdyenCheckoutEx.Model.Installments2, options)
    |> deserialize(:"shopperInput", :struct, AdyenCheckoutEx.Model.ShopperInput, options)
  end
end

