# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.DetailsRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"details",
    :"paymentData",
    :"threeDSAuthenticationOnly"
  ]

  @type t :: %__MODULE__{
    :"details" => AdyenCheckoutEx.Model.PaymentCompletionDetails.t,
    :"paymentData" => String.t | nil,
    :"threeDSAuthenticationOnly" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.DetailsRequest do
  import AdyenCheckoutEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"details", :struct, AdyenCheckoutEx.Model.PaymentCompletionDetails, options)
  end
end

