# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.DeviceRenderOptions do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"sdkInterface",
    :"sdkUiType"
  ]

  @type t :: %__MODULE__{
    :"sdkInterface" => String.t | nil,
    :"sdkUiType" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.DeviceRenderOptions do
  def decode(value, _options) do
    value
  end
end

