# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.DokuDetails do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"firstName",
    :"lastName",
    :"shopperEmail",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"firstName" => String.t,
    :"lastName" => String.t,
    :"shopperEmail" => String.t,
    :"type" => String.t
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.DokuDetails do
  def decode(value, _options) do
    value
  end
end

