# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.ForexQuote do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"account",
    :"accountType",
    :"baseAmount",
    :"basePoints",
    :"buy",
    :"interbank",
    :"reference",
    :"sell",
    :"signature",
    :"source",
    :"type",
    :"validTill"
  ]

  @type t :: %__MODULE__{
    :"account" => String.t | nil,
    :"accountType" => String.t | nil,
    :"baseAmount" => AdyenCheckoutEx.Model.Amount.t | nil,
    :"basePoints" => integer(),
    :"buy" => AdyenCheckoutEx.Model.Amount.t | nil,
    :"interbank" => AdyenCheckoutEx.Model.Amount.t | nil,
    :"reference" => String.t | nil,
    :"sell" => AdyenCheckoutEx.Model.Amount.t | nil,
    :"signature" => String.t | nil,
    :"source" => String.t | nil,
    :"type" => String.t | nil,
    :"validTill" => DateTime.t
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.ForexQuote do
  import AdyenCheckoutEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"baseAmount", :struct, AdyenCheckoutEx.Model.Amount, options)
    |> deserialize(:"buy", :struct, AdyenCheckoutEx.Model.Amount, options)
    |> deserialize(:"interbank", :struct, AdyenCheckoutEx.Model.Amount, options)
    |> deserialize(:"sell", :struct, AdyenCheckoutEx.Model.Amount, options)
  end
end

