# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.InstallmentOption do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"maxValue",
    :"plans",
    :"preselectedValue",
    :"values"
  ]

  @type t :: %__MODULE__{
    :"maxValue" => integer() | nil,
    :"plans" => [String.t] | nil,
    :"preselectedValue" => integer() | nil,
    :"values" => [integer()] | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.InstallmentOption do
  def decode(value, _options) do
    value
  end
end

