# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.LineItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"amountExcludingTax",
    :"amountIncludingTax",
    :"description",
    :"id",
    :"imageUrl",
    :"productUrl",
    :"quantity",
    :"taxAmount",
    :"taxCategory",
    :"taxPercentage"
  ]

  @type t :: %__MODULE__{
    :"amountExcludingTax" => integer() | nil,
    :"amountIncludingTax" => integer() | nil,
    :"description" => String.t | nil,
    :"id" => String.t | nil,
    :"imageUrl" => String.t | nil,
    :"productUrl" => String.t | nil,
    :"quantity" => integer() | nil,
    :"taxAmount" => integer() | nil,
    :"taxCategory" => String.t | nil,
    :"taxPercentage" => integer() | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.LineItem do
  def decode(value, _options) do
    value
  end
end

