# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.MerchantRiskIndicator do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"addressMatch",
    :"deliveryAddressIndicator",
    :"deliveryEmail",
    :"deliveryTimeframe",
    :"giftCardAmount",
    :"giftCardCount",
    :"preOrderDate",
    :"preOrderPurchase",
    :"reorderItems"
  ]

  @type t :: %__MODULE__{
    :"addressMatch" => boolean() | nil,
    :"deliveryAddressIndicator" => String.t | nil,
    :"deliveryEmail" => String.t | nil,
    :"deliveryTimeframe" => String.t | nil,
    :"giftCardAmount" => AdyenCheckoutEx.Model.Amount.t | nil,
    :"giftCardCount" => integer() | nil,
    :"preOrderDate" => DateTime.t | nil,
    :"preOrderPurchase" => boolean() | nil,
    :"reorderItems" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.MerchantRiskIndicator do
  import AdyenCheckoutEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"giftCardAmount", :struct, AdyenCheckoutEx.Model.Amount, options)
  end
end

