# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.MerchantDevice do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"os",
    :"osVersion",
    :"reference"
  ]

  @type t :: %__MODULE__{
    :"os" => String.t | nil,
    :"osVersion" => String.t | nil,
    :"reference" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.MerchantDevice do
  def decode(value, _options) do
    value
  end
end

