# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.MolPayDetails do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"issuer",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"issuer" => String.t,
    :"type" => String.t
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.MolPayDetails do
  def decode(value, _options) do
    value
  end
end

