# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.Name do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"firstName",
    :"infix",
    :"lastName"
  ]

  @type t :: %__MODULE__{
    :"firstName" => String.t,
    :"infix" => String.t | nil,
    :"lastName" => String.t
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.Name do
  def decode(value, _options) do
    value
  end
end

