# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.PayPalDetails do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"orderID",
    :"payerID",
    :"recurringDetailReference",
    :"storedPaymentMethodId",
    :"subtype",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"orderID" => String.t | nil,
    :"payerID" => String.t | nil,
    :"recurringDetailReference" => String.t | nil,
    :"storedPaymentMethodId" => String.t | nil,
    :"subtype" => String.t | nil,
    :"type" => String.t
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.PayPalDetails do
  def decode(value, _options) do
    value
  end
end

