# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.PaymentVerificationResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"additionalData",
    :"fraudResult",
    :"merchantReference",
    :"order",
    :"paymentMethod",
    :"pspReference",
    :"refusalReason",
    :"refusalReasonCode",
    :"resultCode",
    :"serviceError",
    :"shopperLocale"
  ]

  @type t :: %__MODULE__{
    :"additionalData" => %{optional(String.t) => String.t} | nil,
    :"fraudResult" => AdyenCheckoutEx.Model.FraudResult.t | nil,
    :"merchantReference" => String.t,
    :"order" => AdyenCheckoutEx.Model.CheckoutOrderResponse.t | nil,
    :"paymentMethod" => String.t,
    :"pspReference" => String.t | nil,
    :"refusalReason" => String.t | nil,
    :"refusalReasonCode" => String.t | nil,
    :"resultCode" => String.t | nil,
    :"serviceError" => AdyenCheckoutEx.Model.ServiceError2.t | nil,
    :"shopperLocale" => String.t
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.PaymentVerificationResponse do
  import AdyenCheckoutEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"fraudResult", :struct, AdyenCheckoutEx.Model.FraudResult, options)
    |> deserialize(:"order", :struct, AdyenCheckoutEx.Model.CheckoutOrderResponse, options)
    |> deserialize(:"serviceError", :struct, AdyenCheckoutEx.Model.ServiceError2, options)
  end
end

