# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.PaymentMethodsRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"additionalData",
    :"allowedPaymentMethods",
    :"amount",
    :"blockedPaymentMethods",
    :"channel",
    :"countryCode",
    :"merchantAccount",
    :"order",
    :"shopperLocale",
    :"shopperReference",
    :"splitCardFundingSources",
    :"store"
  ]

  @type t :: %__MODULE__{
    :"additionalData" => %{optional(String.t) => String.t} | nil,
    :"allowedPaymentMethods" => [String.t] | nil,
    :"amount" => AdyenCheckoutEx.Model.Amount.t | nil,
    :"blockedPaymentMethods" => [String.t] | nil,
    :"channel" => String.t | nil,
    :"countryCode" => String.t | nil,
    :"merchantAccount" => String.t,
    :"order" => AdyenCheckoutEx.Model.CheckoutOrder.t | nil,
    :"shopperLocale" => String.t | nil,
    :"shopperReference" => String.t | nil,
    :"splitCardFundingSources" => boolean() | nil,
    :"store" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.PaymentMethodsRequest do
  import AdyenCheckoutEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"amount", :struct, AdyenCheckoutEx.Model.Amount, options)
    |> deserialize(:"order", :struct, AdyenCheckoutEx.Model.CheckoutOrder, options)
  end
end

