# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.PaymentSetupResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"paymentSession",
    :"recurringDetails"
  ]

  @type t :: %__MODULE__{
    :"paymentSession" => String.t | nil,
    :"recurringDetails" => [AdyenCheckoutEx.Model.RecurringDetail.t] | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.PaymentSetupResponse do
  import AdyenCheckoutEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"recurringDetails", :list, AdyenCheckoutEx.Model.RecurringDetail, options)
  end
end

