# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.PaymentSetupRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"additionalData",
    :"allowedPaymentMethods",
    :"amount",
    :"applicationInfo",
    :"billingAddress",
    :"blockedPaymentMethods",
    :"captureDelayHours",
    :"channel",
    :"company",
    :"configuration",
    :"conversionId",
    :"countryCode",
    :"dateOfBirth",
    :"dccQuote",
    :"deliveryAddress",
    :"deliveryDate",
    :"enableOneClick",
    :"enablePayOut",
    :"enableRecurring",
    :"entityType",
    :"fraudOffset",
    :"installments",
    :"lineItems",
    :"mandate",
    :"mcc",
    :"merchantAccount",
    :"merchantOrderReference",
    :"metadata",
    :"orderReference",
    :"origin",
    :"recurringExpiry",
    :"recurringFrequency",
    :"reference",
    :"returnUrl",
    :"riskData",
    :"sdkVersion",
    :"sessionValidity",
    :"shopperEmail",
    :"shopperIP",
    :"shopperInteraction",
    :"shopperLocale",
    :"shopperName",
    :"shopperReference",
    :"shopperStatement",
    :"socialSecurityNumber",
    :"splits",
    :"store",
    :"storePaymentMethod",
    :"telephoneNumber",
    :"threeDSAuthenticationOnly",
    :"token",
    :"trustedShopper"
  ]

  @type t :: %__MODULE__{
    :"additionalData" => %{optional(String.t) => String.t} | nil,
    :"allowedPaymentMethods" => [String.t] | nil,
    :"amount" => AdyenCheckoutEx.Model.Amount.t,
    :"applicationInfo" => AdyenCheckoutEx.Model.ApplicationInfo.t | nil,
    :"billingAddress" => AdyenCheckoutEx.Model.Address.t | nil,
    :"blockedPaymentMethods" => [String.t] | nil,
    :"captureDelayHours" => integer() | nil,
    :"channel" => String.t | nil,
    :"company" => AdyenCheckoutEx.Model.Company.t | nil,
    :"configuration" => AdyenCheckoutEx.Model.Configuration.t | nil,
    :"conversionId" => String.t | nil,
    :"countryCode" => String.t,
    :"dateOfBirth" => DateTime.t | nil,
    :"dccQuote" => AdyenCheckoutEx.Model.ForexQuote.t | nil,
    :"deliveryAddress" => AdyenCheckoutEx.Model.Address.t | nil,
    :"deliveryDate" => DateTime.t | nil,
    :"enableOneClick" => boolean() | nil,
    :"enablePayOut" => boolean() | nil,
    :"enableRecurring" => boolean() | nil,
    :"entityType" => String.t | nil,
    :"fraudOffset" => integer() | nil,
    :"installments" => AdyenCheckoutEx.Model.Installments.t | nil,
    :"lineItems" => [AdyenCheckoutEx.Model.LineItem.t] | nil,
    :"mandate" => AdyenCheckoutEx.Model.Mandate.t | nil,
    :"mcc" => String.t | nil,
    :"merchantAccount" => String.t,
    :"merchantOrderReference" => String.t | nil,
    :"metadata" => %{optional(String.t) => String.t} | nil,
    :"orderReference" => String.t | nil,
    :"origin" => String.t | nil,
    :"recurringExpiry" => String.t | nil,
    :"recurringFrequency" => String.t | nil,
    :"reference" => String.t,
    :"returnUrl" => String.t,
    :"riskData" => AdyenCheckoutEx.Model.RiskData.t | nil,
    :"sdkVersion" => String.t | nil,
    :"sessionValidity" => String.t | nil,
    :"shopperEmail" => String.t | nil,
    :"shopperIP" => String.t | nil,
    :"shopperInteraction" => String.t | nil,
    :"shopperLocale" => String.t | nil,
    :"shopperName" => AdyenCheckoutEx.Model.Name.t | nil,
    :"shopperReference" => String.t | nil,
    :"shopperStatement" => String.t | nil,
    :"socialSecurityNumber" => String.t | nil,
    :"splits" => [AdyenCheckoutEx.Model.Split.t] | nil,
    :"store" => String.t | nil,
    :"storePaymentMethod" => boolean() | nil,
    :"telephoneNumber" => String.t | nil,
    :"threeDSAuthenticationOnly" => boolean() | nil,
    :"token" => String.t | nil,
    :"trustedShopper" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.PaymentSetupRequest do
  import AdyenCheckoutEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"amount", :struct, AdyenCheckoutEx.Model.Amount, options)
    |> deserialize(:"applicationInfo", :struct, AdyenCheckoutEx.Model.ApplicationInfo, options)
    |> deserialize(:"billingAddress", :struct, AdyenCheckoutEx.Model.Address, options)
    |> deserialize(:"company", :struct, AdyenCheckoutEx.Model.Company, options)
    |> deserialize(:"configuration", :struct, AdyenCheckoutEx.Model.Configuration, options)
    |> deserialize(:"dccQuote", :struct, AdyenCheckoutEx.Model.ForexQuote, options)
    |> deserialize(:"deliveryAddress", :struct, AdyenCheckoutEx.Model.Address, options)
    |> deserialize(:"installments", :struct, AdyenCheckoutEx.Model.Installments, options)
    |> deserialize(:"lineItems", :list, AdyenCheckoutEx.Model.LineItem, options)
    |> deserialize(:"mandate", :struct, AdyenCheckoutEx.Model.Mandate, options)
    |> deserialize(:"riskData", :struct, AdyenCheckoutEx.Model.RiskData, options)
    |> deserialize(:"shopperName", :struct, AdyenCheckoutEx.Model.Name, options)
    |> deserialize(:"splits", :list, AdyenCheckoutEx.Model.Split, options)
  end
end

