# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.PaymentCompletionDetails do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"MD",
    :"PaReq",
    :"PaRes",
    :"billingToken",
    :"cupsecureplus.smscode",
    :"facilitatorAccessToken",
    :"oneTimePasscode",
    :"orderID",
    :"payerID",
    :"payload",
    :"paymentID",
    :"paymentStatus",
    :"redirectResult",
    :"threeDSResult",
    :"threeds2.challengeResult",
    :"threeds2.fingerprint"
  ]

  @type t :: %__MODULE__{
    :"MD" => String.t | nil,
    :"PaReq" => String.t | nil,
    :"PaRes" => String.t | nil,
    :"billingToken" => String.t | nil,
    :"cupsecureplus.smscode" => String.t | nil,
    :"facilitatorAccessToken" => String.t | nil,
    :"oneTimePasscode" => String.t | nil,
    :"orderID" => String.t | nil,
    :"payerID" => String.t | nil,
    :"payload" => String.t | nil,
    :"paymentID" => String.t | nil,
    :"paymentStatus" => String.t | nil,
    :"redirectResult" => String.t | nil,
    :"threeDSResult" => String.t | nil,
    :"threeds2.challengeResult" => String.t | nil,
    :"threeds2.fingerprint" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.PaymentCompletionDetails do
  def decode(value, _options) do
    value
  end
end

