# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.PaymentLinkResource do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"allowedPaymentMethods",
    :"amount",
    :"applicationInfo",
    :"billingAddress",
    :"blockedPaymentMethods",
    :"countryCode",
    :"deliverAt",
    :"deliveryAddress",
    :"description",
    :"expiresAt",
    :"id",
    :"lineItems",
    :"merchantAccount",
    :"merchantOrderReference",
    :"recurringProcessingModel",
    :"reference",
    :"returnUrl",
    :"reusable",
    :"riskData",
    :"shopperEmail",
    :"shopperLocale",
    :"shopperName",
    :"shopperReference",
    :"splits",
    :"status",
    :"store",
    :"storePaymentMethod",
    :"url"
  ]

  @type t :: %__MODULE__{
    :"allowedPaymentMethods" => [String.t] | nil,
    :"amount" => AdyenCheckoutEx.Model.Amount.t,
    :"applicationInfo" => AdyenCheckoutEx.Model.ApplicationInfo.t | nil,
    :"billingAddress" => AdyenCheckoutEx.Model.Address.t | nil,
    :"blockedPaymentMethods" => [String.t] | nil,
    :"countryCode" => String.t | nil,
    :"deliverAt" => DateTime.t | nil,
    :"deliveryAddress" => AdyenCheckoutEx.Model.Address.t | nil,
    :"description" => String.t | nil,
    :"expiresAt" => String.t | nil,
    :"id" => String.t,
    :"lineItems" => [AdyenCheckoutEx.Model.LineItem.t] | nil,
    :"merchantAccount" => String.t,
    :"merchantOrderReference" => String.t | nil,
    :"recurringProcessingModel" => String.t | nil,
    :"reference" => String.t,
    :"returnUrl" => String.t | nil,
    :"reusable" => boolean() | nil,
    :"riskData" => AdyenCheckoutEx.Model.RiskData.t | nil,
    :"shopperEmail" => String.t | nil,
    :"shopperLocale" => String.t | nil,
    :"shopperName" => AdyenCheckoutEx.Model.Name.t | nil,
    :"shopperReference" => String.t | nil,
    :"splits" => [AdyenCheckoutEx.Model.Split.t] | nil,
    :"status" => String.t,
    :"store" => String.t | nil,
    :"storePaymentMethod" => boolean() | nil,
    :"url" => String.t
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.PaymentLinkResource do
  import AdyenCheckoutEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"amount", :struct, AdyenCheckoutEx.Model.Amount, options)
    |> deserialize(:"applicationInfo", :struct, AdyenCheckoutEx.Model.ApplicationInfo, options)
    |> deserialize(:"billingAddress", :struct, AdyenCheckoutEx.Model.Address, options)
    |> deserialize(:"deliveryAddress", :struct, AdyenCheckoutEx.Model.Address, options)
    |> deserialize(:"lineItems", :list, AdyenCheckoutEx.Model.LineItem, options)
    |> deserialize(:"riskData", :struct, AdyenCheckoutEx.Model.RiskData, options)
    |> deserialize(:"shopperName", :struct, AdyenCheckoutEx.Model.Name, options)
    |> deserialize(:"splits", :list, AdyenCheckoutEx.Model.Split, options)
  end
end

