# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.RecurringDetail do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"brand",
    :"brands",
    :"configuration",
    :"details",
    :"fundingSource",
    :"group",
    :"inputDetails",
    :"name",
    :"recurringDetailReference",
    :"storedDetails",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"brand" => String.t | nil,
    :"brands" => [String.t] | nil,
    :"configuration" => %{optional(String.t) => String.t} | nil,
    :"details" => [AdyenCheckoutEx.Model.InputDetail.t] | nil,
    :"fundingSource" => String.t | nil,
    :"group" => AdyenCheckoutEx.Model.PaymentMethodGroup.t | nil,
    :"inputDetails" => [AdyenCheckoutEx.Model.InputDetail.t] | nil,
    :"name" => String.t | nil,
    :"recurringDetailReference" => String.t | nil,
    :"storedDetails" => AdyenCheckoutEx.Model.StoredDetails.t | nil,
    :"type" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.RecurringDetail do
  import AdyenCheckoutEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"details", :list, AdyenCheckoutEx.Model.InputDetail, options)
    |> deserialize(:"group", :struct, AdyenCheckoutEx.Model.PaymentMethodGroup, options)
    |> deserialize(:"inputDetails", :list, AdyenCheckoutEx.Model.InputDetail, options)
    |> deserialize(:"storedDetails", :struct, AdyenCheckoutEx.Model.StoredDetails, options)
  end
end

