# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.Recurring do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"contract",
    :"recurringDetailName",
    :"recurringExpiry",
    :"recurringFrequency",
    :"tokenService"
  ]

  @type t :: %__MODULE__{
    :"contract" => String.t | nil,
    :"recurringDetailName" => String.t | nil,
    :"recurringExpiry" => DateTime.t | nil,
    :"recurringFrequency" => String.t | nil,
    :"tokenService" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.Recurring do
  def decode(value, _options) do
    value
  end
end

