# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.ResponseAdditionalDataCard do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"cardBin",
    :"cardHolderName",
    :"cardIssuingBank",
    :"cardIssuingCountry",
    :"cardIssuingCurrency",
    :"cardPaymentMethod",
    :"cardSummary"
  ]

  @type t :: %__MODULE__{
    :"cardBin" => String.t | nil,
    :"cardHolderName" => String.t | nil,
    :"cardIssuingBank" => String.t | nil,
    :"cardIssuingCountry" => String.t | nil,
    :"cardIssuingCurrency" => String.t | nil,
    :"cardPaymentMethod" => String.t | nil,
    :"cardSummary" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.ResponseAdditionalDataCard do
  def decode(value, _options) do
    value
  end
end

