# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.ResponseAdditionalDataDeliveryAddress do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"deliveryAddress.city",
    :"deliveryAddress.country",
    :"deliveryAddress.houseNumberOrName",
    :"deliveryAddress.postalCode",
    :"deliveryAddress.stateOrProvince",
    :"deliveryAddress.street"
  ]

  @type t :: %__MODULE__{
    :"deliveryAddress.city" => String.t | nil,
    :"deliveryAddress.country" => String.t | nil,
    :"deliveryAddress.houseNumberOrName" => String.t | nil,
    :"deliveryAddress.postalCode" => String.t | nil,
    :"deliveryAddress.stateOrProvince" => String.t | nil,
    :"deliveryAddress.street" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.ResponseAdditionalDataDeliveryAddress do
  def decode(value, _options) do
    value
  end
end

