# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.ResponseAdditionalDataPayPal do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"paypalEmail",
    :"paypalPayerId",
    :"paypalPayerResidenceCountry",
    :"paypalPayerStatus",
    :"paypalProtectionEligibility"
  ]

  @type t :: %__MODULE__{
    :"paypalEmail" => String.t | nil,
    :"paypalPayerId" => String.t | nil,
    :"paypalPayerResidenceCountry" => String.t | nil,
    :"paypalPayerStatus" => String.t | nil,
    :"paypalProtectionEligibility" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.ResponseAdditionalDataPayPal do
  def decode(value, _options) do
    value
  end
end

