# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.ResponseAdditionalDataCommon do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"acquirerAccountCode",
    :"acquirerCode",
    :"acquirerReference",
    :"alias",
    :"aliasType",
    :"authCode",
    :"authorisedAmountCurrency",
    :"authorisedAmountValue",
    :"avsResult",
    :"avsResultRaw",
    :"bic",
    :"cvcResult",
    :"cvcResultRaw",
    :"dsTransID",
    :"eci",
    :"expiryDate",
    :"extraCostsCurrency",
    :"extraCostsValue",
    :"fraudCheck-[itemNr]-[FraudCheckname]",
    :"fundingSource",
    :"fundsAvailability",
    :"inferredRefusalReason",
    :"issuerCountry",
    :"mcBankNetReferenceNumber",
    :"networkTxReference",
    :"ownerName",
    :"paymentAccountReference",
    :"paymentMethodVariant",
    :"payoutEligible",
    :"realtimeAccountUpdaterStatus",
    :"receiptFreeText",
    :"recurring.firstPspReference",
    :"recurring.recurringDetailReference",
    :"recurring.shopperReference",
    :"recurringProcessingModel",
    :"referred",
    :"refusalReasonRaw",
    :"shopperInteraction",
    :"shopperReference",
    :"terminalId",
    :"threeDAuthenticated",
    :"threeDAuthenticatedResponse",
    :"threeDOffered",
    :"threeDOfferedResponse",
    :"threeDSVersion",
    :"visaTransactionId",
    :"xid"
  ]

  @type t :: %__MODULE__{
    :"acquirerAccountCode" => String.t | nil,
    :"acquirerCode" => String.t | nil,
    :"acquirerReference" => String.t | nil,
    :"alias" => String.t | nil,
    :"aliasType" => String.t | nil,
    :"authCode" => String.t | nil,
    :"authorisedAmountCurrency" => String.t | nil,
    :"authorisedAmountValue" => String.t | nil,
    :"avsResult" => String.t | nil,
    :"avsResultRaw" => String.t | nil,
    :"bic" => String.t | nil,
    :"cvcResult" => String.t | nil,
    :"cvcResultRaw" => String.t | nil,
    :"dsTransID" => String.t | nil,
    :"eci" => String.t | nil,
    :"expiryDate" => String.t | nil,
    :"extraCostsCurrency" => String.t | nil,
    :"extraCostsValue" => String.t | nil,
    :"fraudCheck-[itemNr]-[FraudCheckname]" => String.t | nil,
    :"fundingSource" => String.t | nil,
    :"fundsAvailability" => String.t | nil,
    :"inferredRefusalReason" => String.t | nil,
    :"issuerCountry" => String.t | nil,
    :"mcBankNetReferenceNumber" => String.t | nil,
    :"networkTxReference" => String.t | nil,
    :"ownerName" => String.t | nil,
    :"paymentAccountReference" => String.t | nil,
    :"paymentMethodVariant" => String.t | nil,
    :"payoutEligible" => String.t | nil,
    :"realtimeAccountUpdaterStatus" => String.t | nil,
    :"receiptFreeText" => String.t | nil,
    :"recurring.firstPspReference" => String.t | nil,
    :"recurring.recurringDetailReference" => String.t | nil,
    :"recurring.shopperReference" => String.t | nil,
    :"recurringProcessingModel" => String.t | nil,
    :"referred" => String.t | nil,
    :"refusalReasonRaw" => String.t | nil,
    :"shopperInteraction" => String.t | nil,
    :"shopperReference" => String.t | nil,
    :"terminalId" => String.t | nil,
    :"threeDAuthenticated" => String.t | nil,
    :"threeDAuthenticatedResponse" => String.t | nil,
    :"threeDOffered" => String.t | nil,
    :"threeDOfferedResponse" => String.t | nil,
    :"threeDSVersion" => String.t | nil,
    :"visaTransactionId" => String.t | nil,
    :"xid" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.ResponseAdditionalDataCommon do
  def decode(value, _options) do
    value
  end
end

