# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.ResponseAdditionalDataInstallments do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"installmentPaymentData.installmentType",
    :"installmentPaymentData.option[itemNr].annualPercentageRate",
    :"installmentPaymentData.option[itemNr].firstInstallmentAmount",
    :"installmentPaymentData.option[itemNr].installmentFee",
    :"installmentPaymentData.option[itemNr].interestRate",
    :"installmentPaymentData.option[itemNr].maximumNumberOfInstallments",
    :"installmentPaymentData.option[itemNr].minimumNumberOfInstallments",
    :"installmentPaymentData.option[itemNr].numberOfInstallments",
    :"installmentPaymentData.option[itemNr].subsequentInstallmentAmount",
    :"installmentPaymentData.option[itemNr].totalAmountDue",
    :"installmentPaymentData.paymentOptions",
    :"installments.value"
  ]

  @type t :: %__MODULE__{
    :"installmentPaymentData.installmentType" => String.t | nil,
    :"installmentPaymentData.option[itemNr].annualPercentageRate" => String.t | nil,
    :"installmentPaymentData.option[itemNr].firstInstallmentAmount" => String.t | nil,
    :"installmentPaymentData.option[itemNr].installmentFee" => String.t | nil,
    :"installmentPaymentData.option[itemNr].interestRate" => String.t | nil,
    :"installmentPaymentData.option[itemNr].maximumNumberOfInstallments" => String.t | nil,
    :"installmentPaymentData.option[itemNr].minimumNumberOfInstallments" => String.t | nil,
    :"installmentPaymentData.option[itemNr].numberOfInstallments" => String.t | nil,
    :"installmentPaymentData.option[itemNr].subsequentInstallmentAmount" => String.t | nil,
    :"installmentPaymentData.option[itemNr].totalAmountDue" => String.t | nil,
    :"installmentPaymentData.paymentOptions" => String.t | nil,
    :"installments.value" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.ResponseAdditionalDataInstallments do
  def decode(value, _options) do
    value
  end
end

