# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.ResponseAdditionalDataSepa do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"sepadirectdebit.dateOfSignature",
    :"sepadirectdebit.mandateId",
    :"sepadirectdebit.sequenceType"
  ]

  @type t :: %__MODULE__{
    :"sepadirectdebit.dateOfSignature" => String.t | nil,
    :"sepadirectdebit.mandateId" => String.t | nil,
    :"sepadirectdebit.sequenceType" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.ResponseAdditionalDataSepa do
  def decode(value, _options) do
    value
  end
end

