# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.ResponseAdditionalData3DSecure do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"cardHolderInfo",
    :"scaExemptionRequested"
  ]

  @type t :: %__MODULE__{
    :"cardHolderInfo" => String.t | nil,
    :"scaExemptionRequested" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.ResponseAdditionalData3DSecure do
  def decode(value, _options) do
    value
  end
end

