# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.ResponseAdditionalDataBillingAddress do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"billingAddress.city",
    :"billingAddress.country",
    :"billingAddress.houseNumberOrName",
    :"billingAddress.postalCode",
    :"billingAddress.stateOrProvince",
    :"billingAddress.street"
  ]

  @type t :: %__MODULE__{
    :"billingAddress.city" => String.t | nil,
    :"billingAddress.country" => String.t | nil,
    :"billingAddress.houseNumberOrName" => String.t | nil,
    :"billingAddress.postalCode" => String.t | nil,
    :"billingAddress.stateOrProvince" => String.t | nil,
    :"billingAddress.street" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.ResponseAdditionalDataBillingAddress do
  def decode(value, _options) do
    value
  end
end

