# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.SdkEphemPubKey do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"crv",
    :"kty",
    :"x",
    :"y"
  ]

  @type t :: %__MODULE__{
    :"crv" => String.t | nil,
    :"kty" => String.t | nil,
    :"x" => String.t | nil,
    :"y" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.SdkEphemPubKey do
  def decode(value, _options) do
    value
  end
end

