# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.Split do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"account",
    :"amount",
    :"description",
    :"reference",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"account" => String.t | nil,
    :"amount" => AdyenCheckoutEx.Model.SplitAmount.t,
    :"description" => String.t | nil,
    :"reference" => String.t | nil,
    :"type" => String.t
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.Split do
  import AdyenCheckoutEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"amount", :struct, AdyenCheckoutEx.Model.SplitAmount, options)
  end
end

