# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.StoredDetails do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"bank",
    :"card",
    :"emailAddress"
  ]

  @type t :: %__MODULE__{
    :"bank" => AdyenCheckoutEx.Model.BankAccount.t | nil,
    :"card" => AdyenCheckoutEx.Model.Card.t | nil,
    :"emailAddress" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.StoredDetails do
  import AdyenCheckoutEx.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"bank", :struct, AdyenCheckoutEx.Model.BankAccount, options)
    |> deserialize(:"card", :struct, AdyenCheckoutEx.Model.Card, options)
  end
end

