# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.StoredPaymentMethod do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"brand",
    :"expiryMonth",
    :"expiryYear",
    :"holderName",
    :"iban",
    :"id",
    :"lastFour",
    :"name",
    :"ownerName",
    :"shopperEmail",
    :"supportedShopperInteractions",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"brand" => String.t | nil,
    :"expiryMonth" => String.t | nil,
    :"expiryYear" => String.t | nil,
    :"holderName" => String.t | nil,
    :"iban" => String.t | nil,
    :"id" => String.t | nil,
    :"lastFour" => String.t | nil,
    :"name" => String.t | nil,
    :"ownerName" => String.t | nil,
    :"shopperEmail" => String.t | nil,
    :"supportedShopperInteractions" => [String.t] | nil,
    :"type" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.StoredPaymentMethod do
  def decode(value, _options) do
    value
  end
end

