# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenCheckoutEx.Model.WeChatPayMiniProgramDetails do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"appId",
    :"openid",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"appId" => String.t | nil,
    :"openid" => String.t | nil,
    :"type" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenCheckoutEx.Model.WeChatPayMiniProgramDetails do
  def decode(value, _options) do
    value
  end
end

